# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://harrisonhadaway.github.io/
 
title: Harrison Hadaway
author: Harrison Hadaway
description: Personal blog and resume
avatar: profile.png
email: harrisonleehadaway@gmail.com
github: harrisonhadaway # username
twitter: hadaway903
linkedin: harrisonhadaway
#stackoverflow: us   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 



# needed for travis-ci build
exclude: [vendor]
